name: Build WhatsMeow DLL

on:
  workflow_dispatch:
    inputs:
      whatsmeow_version:
        description: "WhatsMeow version"
        required: false
        default: "latest"

jobs:
  build-windows-amd64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "^1.21.5"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: mlugg/setup-zig@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --dev

      - name: Update WhatsMeow
        run: |
          cd goneonize
          go get go.mau.fi/whatsmeow@${{ inputs.whatsmeow_version }}
          go mod tidy

      - name: Build Windows AMD64 DLL
        run: |
          export CGO_ENABLED=1
          export GOOS=windows
          export GOARCH=amd64
          export CC="zig cc -target x86_64-windows"
          uv run task build goneonize

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: neonize-windows-amd64
          path: neonize/neonize-windows-amd64.dll
